# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixel_app', '0002_auto_20181004_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pixel_app.Comment'),
        ),
    ]
